import QtQuick
import Quickshell
import Quickshell.Io
import qs.config

QtObject {
    id: root

    function _schemeScript() {
        const isLight = !!Config.lightMode
        const colorScheme = isLight ? "prefer-light" : "prefer-dark"
        const gtkTheme = isLight ? "adw-gtk3" : "adw-gtk3-dark"
        const preferDark = isLight ? "false" : "true"
        const home = Quickshell.env("HOME")
        const gtk3Dir = home + "/.config/gtk-3.0"
        const gtk4Dir = home + "/.config/gtk-4.0"

        // Escape ${...} so QML/JS does not interpolate shell variables.
        return `
update_ini_key() {
    file="$1"
    key="$2"
    val="$3"
    mkdir -p "$(dirname "$file")"
    if [ ! -f "$file" ]; then
        printf '[Settings]\\n%s=%s\\n' "$key" "$val" > "$file"
        return
    fi
    if grep -q "^\${key}=" "$file"; then
        sed -i "s|^\${key}=.*|\${key}=\${val}|" "$file"
    elif grep -q '^\\[Settings\\]' "$file"; then
        sed -i "/^\\[Settings\\]/a \${key}=\${val}" "$file"
    else
        printf '\\n[Settings]\\n%s=%s\\n' "$key" "$val" >> "$file"
    fi
}

mkdir -p "${gtk3Dir}" "${gtk4Dir}"

if command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface color-scheme '${colorScheme}' || true
    gsettings set org.gnome.desktop.interface gtk-theme "" || true
    gsettings set org.gnome.desktop.interface gtk-theme '${gtkTheme}' || true
fi

update_ini_key "${gtk3Dir}/settings.ini" "gtk-application-prefer-dark-theme" "${preferDark}"
update_ini_key "${gtk3Dir}/settings.ini" "gtk-theme-name" "${gtkTheme}"
update_ini_key "${gtk4Dir}/settings.ini" "gtk-application-prefer-dark-theme" "${preferDark}"
update_ini_key "${gtk4Dir}/settings.ini" "gtk-theme-name" "${gtkTheme}"
`
    }

    function syncSystemScheme() {
        schemeProcess.command = ["sh", "-c", root._schemeScript()]
        schemeProcess.running = true
    }

    function generate(Colors) {
        if (!Colors) return

        const fmt = (c) => c.toString()
        const toRgba = (c, a) => `rgba(${Math.round(c.r * 255)}, ${Math.round(c.g * 255)}, ${Math.round(c.b * 255)}, ${a})`

        const primary = fmt(Colors.primary)
        const onPrimary = fmt(Colors.overPrimary)
        const background = toRgba(Colors.background, Config.theme.srBg.opacity)
        const onBackground = fmt(Colors.overBackground)
        const surface = fmt(Colors.surface)
        const onSurface = fmt(Colors.overSurface)
        const surfaceContainer = fmt(Colors.surfaceContainer)

        let css = "/* GTK Colors generated by Ambxst */\n\n"

        css += `@define-color accent_color ${primary};\n`
        css += `@define-color accent_fg_color ${onPrimary};\n`
        css += `@define-color accent_bg_color ${primary};\n`
        css += `@define-color window_bg_color ${background};\n`
        css += `@define-color window_fg_color ${onBackground};\n`
        css += `@define-color headerbar_bg_color ${background};\n`
        css += `@define-color headerbar_fg_color ${onBackground};\n`
        css += `@define-color popover_bg_color ${surface};\n`
        css += `@define-color popover_fg_color ${onSurface};\n`
        css += `@define-color view_bg_color ${background};\n`
        css += `@define-color view_fg_color ${onBackground};\n`
        css += `@define-color card_bg_color ${surfaceContainer};\n`
        css += `@define-color card_fg_color ${onSurface};\n`

        // Sidebar typically matches window or has slight contrast.
        // Using window variables as reference.
        css += `@define-color sidebar_bg_color @window_bg_color;\n`
        css += `@define-color sidebar_fg_color @window_fg_color;\n`
        css += `@define-color sidebar_border_color @window_bg_color;\n`
        css += `@define-color sidebar_backdrop_color @window_bg_color;\n`

        const home = Quickshell.env("HOME")
        const gtk3Dir = home + "/.config/gtk-3.0"
        const gtk4Dir = home + "/.config/gtk-4.0"

        writer.text = css

        // Write GTK CSS, then apply system-wide color-scheme / theme preference
        const cmd = `
mkdir -p "${gtk3Dir}" "${gtk4Dir}" && \\
echo "${css}" | tee "${gtk3Dir}/gtk.css" "${gtk4Dir}/gtk.css" > /dev/null
` + root._schemeScript()

        writerProcess.command = ["sh", "-c", cmd]
        writerProcess.running = true
    }

    property QtObject writer: QtObject {
        id: writer
        property string text
    }

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("GtkGenerator: Colors and system color-scheme generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: (err) => {
                if (err) console.error("GtkGenerator Error:", err)
            }
        }
    }

    property Process schemeProcess: Process {
        id: schemeProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("GtkGenerator: System color-scheme synced.")
        }
        stderr: StdioCollector {
            onStreamFinished: (err) => {
                if (err) console.error("GtkGenerator scheme sync error:", err)
            }
        }
    }
}
